plugins {
    alias(libs.plugins.loom)
    id 'idea'
    id 'maven-publish'
}

def javaVersion = 21

base {
    archivesName = project.mod_id
}

version = project.mod_version
group = project.maven_group

sourceSets {
    test
}

loom {
    splitEnvironmentSourceSets()
}

fabricApi {
    configureDataGeneration {
        client = true
        createSourceSet = true
        modId = "${mod_id}-datagen"
    }
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")

    runs {
        client {
            client()

            name = "Minecraft Client"
//            programArgs "--username", "HatsuneMiku"
//            programArgs "--uuid", "534e8d1c-5d83-4c56-a35d-b8f968ddcd01"
            programArgs "--width", "1280"
            programArgs "--height", "800"

            vmArg "-D${mod_id}.debug"
            vmArg "-Dfabric-tag-conventions-v2.missingTagTranslationWarning=VERBOSE"
        }
	}

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

idea {
    module {
        inheritOutputDirs = false
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'Sonatype Snapshots'
        url = 'https://oss.sonatype.org/content/repositories/snapshots'
    }

    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven'
            }
        }
        filter {
            includeGroup('software.bernie.geckolib')
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'SmartBrainLib (SBL) Maven Repo'
                url = 'https://dl.cloudsmith.io/public/tslat/sbl/mave'
            }
        }
        filter {
            includeGroup('net.tslat.smartbrainlib')
        }
    }
    maven {
        name = "rei"
        url = "https://maven.shedaniel.me"
    }
    maven {
        name = "BlameJared Maven"
        url = "https://maven.blamejared.com"
    }
    // https://github.com/Ladysnake/Impersonate/tree/1.20.1
    maven {
        name = "Ladysnake Mods"
        url = "https://maven.ladysnake.org/releases"
        content {
            includeGroup 'io.github.ladysnake'
            includeGroupAndSubgroups 'org.ladysnake'
            includeGroupAndSubgroups 'dev.onyxstudios'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Curseforge"
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Jitpack"
        url = "https://jitpack.io"
    }
}

dependencies {
    minecraft libs.minecraft
    mappings "${libs.yarn.get()}:v2"
    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api

    compileOnly libs.jetbrains.annotations

    modImplementation(include("com.terraformersmc.terraform-api:terraform-wood-api-v1:${terraform_wood_api_version}"))
    modImplementation(include('com.github.Chocohead:Fabric-ASM:v2.3'))

    modImplementation "software.bernie.geckolib:geckolib-fabric-${geckolib_version}"
//    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${minecraft_version}:${sbl_version}"
//    modImplementation "dev.emi:trinkets:${trinkets_version}"
    modImplementation "maven.modrinth:fusion-connected-textures:${fusion_version}-fabric-mc${minecraft_version}"

    // EMI
//    modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
//    modLocalRuntime "dev.emi:emi-fabric:${emi_version}"

    // REI
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"

//    if (findProperty("has_local_suggestionproviderfix")) {
//        modRuntimeOnly("xyz.deftu:SuggestionProviderFix:1.0.0")
//    }

    // Nice dev things
	modRuntimeOnly "curse.maven:disablecustomworldsadvice-401978:5510699"
    // https://www.curseforge.com/minecraft/mc-mods/debug-utils-fabric/files/4644075
    modRuntimeOnly "curse.maven:debugutils-783010:6585499"
    modRuntimeOnly "maven.modrinth:worldgen-devtools:1.3.2+1.21.4"

    // Testing compat
//    modRuntimeOnly "maven.modrinth:sodium:mc1.20.1-0.5.8"
    modCompileOnly "maven.modrinth:iris:1.8.8+1.21.4-fabric"

    // Bewitchment
//    modImplementation("curse.maven:bewitchment-394915:${bewitchment_fileid}")
//    modImplementation("com.github.virtuoel:pehkui:${pehkui_version}")
//    modImplementation("vazkii.patchouli:Patchouli:${patchouli_version}")
//    modImplementation("maven.modrinth:midnightlib:${midnightlib_version}")
//    modImplementation("io.github.ladysnake:PlayerAbilityLib:${pal_version}")
//    modImplementation("me.lucko:fabric-permissions-api:${fabric_permissions_api_version}")
//    modImplementation("org.ladysnake:impersonate:${impersonate_version}") {
//        transitive = false
//    }
}

processResources {
    exclude(".cache")
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = javaVersion
}

java {
    withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename ("LICENSE", "LICENSE_${inputs.properties.archivesName}")
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
